config/routes.rb
Rails.application.routes.draw do

  resource :user, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
  resources :bands do
  	resources :albums, only: :new
  end

  resources :albums, except: [:new, :index] do
  	resources :tracks, only: :new
  end

  resources :tracks, except: [:new, :index] do
  	resources :notes, only: :new
  end
  resources :notes, except: [:new, :index, :edit, :update]
  root 'users#show'

end

app/models/album.rb
class Album < ActiveRecord::Base

	validates :name, :band_id, presence: true
	validates :edition, inclusion: { in: %w(Live Studio) }

	belongs_to(
		:band,
		class_name: "Band",
		foreign_key: :band_id,
		primary_key: :id
	)

	has_many(
		:tracks,
		class_name: "Track",
		foreign_key: :album_id,
		primary_key: :id,
		dependent: :destroy
	)
end

app/models/band.rb
class Band < ActiveRecord::Base
	has_many(
		:albums,
		class_name: "Album",
		foreign_key: :band_id,
		primary_key: :id,
		dependent: :destroy
	)

	has_many(
		:tracks,
		through: :albums,
		source: :tracks
	)
end

app/models/note.rb
class Note < ActiveRecord::Base
	validates :user_id, :track_id, :note_text, presence: true

	belongs_to(
		:user,
		class_name: "User",
		foreign_key: :user_id,
		primary_key: :id
	)

	belongs_to(
		:track,
		class_name: "Track",
		foreign_key: :track_id,
		primary_key: :id
	)
end

app/models/track.rb
class Track < ActiveRecord::Base
	validates :name, :album_id, :lyrics, presence: true
	validates :edition, inclusion: { in: %w(Regular Bonus)}

	belongs_to(
		:album,
		class_name: "Album",
		foreign_key: :album_id,
		primary_key: :id
	)

	has_many(
		:notes,
		class_name: "Note",
		foreign_key: :track_id,
		primary_key: :id
	)
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_reader :password

	# called only when you try to #save/create or #valid? 
	validates :email, presence: true, uniqueness: true
	validates :password_digest, presence: { message: "Password can't be blank" }
	validates :session_token, presence: true, uniqueness: true
	validates :password, length: { minimum: 6, allow_nil: true }

	# called after User.new but before @user.save!
	after_initialize :ensure_session_token

	has_many(
		:notes,
		class_name: "Note",
		foreign_key: :user_id,
		primary_key: :id
	)

	def self.find_by_credentials(user_email, user_password)
		found_user = self.find_by_email(user_email)
		if found_user.nil?
			# errors[:request] = "No such e-mail found!"
			return nil
		else
			if found_user.is_password?(user_password)
				return found_user
			else
				# errors[:request] = "Incorrect password!"
				return nil
			end
		end
	end

	def self.generate_session_token
		SecureRandom::urlsafe_base64(16)
	end

	def password=(set_password)
		@password = set_password
		self.password_digest = BCrypt::Password.create(set_password)	
	end

	def is_password?(password)
    	BCrypt::Password.new(self.password_digest).is_password?(password)
  	end
  

	def reset_session_token!
		self.session_token = self.class.generate_session_token
		self.save!

		self.session_token
	end


	private
		def ensure_session_token
			self.session_token ||= self.class.generate_session_token
		end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	before_action :logged_in
	
	def show
		@album = Album.find(params[:id])
	end

	def new
		@album = Album.new
		render :new
	end

	def edit
		@album = Album.find(params[:id])
		
		render :edit
	end

	def create
		@album = Album.new(album_params)
		if @album.save
			redirect_to album_url(@album)
		else
			flash[:errors] = @album.errors.full_messages
			render :new
		end
	end

	def update
		@album = Album.find(params[:id])
		if @album.update(album_params)
			redirect_to album_url(@album)
		else
			flash[:errors] = @album.errors.full_messages
			render :edit
		end
	end

	def destroy
		@album = Album.find(params[:id])
		@album.destroy!

		redirect_to band_url(Band.find(@album.band_id))
	end

	private
		def album_params
			params.require(:album).permit(:name, :band_id, :edition)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
  	return nil if session[:session_token].nil?
  	@current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login!(user)
  	@current_user = user
  	session[:session_token] = user.session_token
  end

  def logged_in
    redirect_to new_session_url if current_user.nil?
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
	before_action :logged_in

	def index
		@bands = Band.all
		render :index
	end

	def show
		@band = Band.find(params[:id])
		render :show
	end

	def new
		@band = Band.new
		render :new
	end

	def edit
		@band = Band.find(params[:id])
		render :edit
	end

	def create
		@band = Band.new(band_params)
		if @band.save!
			redirect_to band_url(@band)
		else
			flash[:errors] = @band.errors.full_messages
			render :new
		end
	end

	def update
		@band = Band.find(params[:id])
		if @band.update!(band_params)
			redirect_to band_url(@band)
		else
			render :edit
		end
	end

	def destroy
		@band = Band.find(params[:id])
		@band.destroy!

		redirect_to bands_url
	end
	
	private
		def band_params
			params.require(:band).permit(:name)
		end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	def create
		@note = Note.new(note_params)
		@note.user_id = current_user.id
		if @note.save
			redirect_to track_url(@note.track_id)
		else
			flash[:errors] = @note.errors.full_messages
			redirect_to(:back)
		end
	end

	def destroy
		@note = Note.find(params[:id])
		if current_user.id == @note.user_id
			@note.destroy!
			redirect_to track_url(@note.track_id)
		else
			raise ActionController::RoutingError.new('Forbidden')
		end
	end

	private
		def note_params
			params.require(:note).permit(:user_id, :track_id, :note_text)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@user = User.new
		render :new
	end

	def create
		@user = User.find_by_credentials(
			params[:user][:email], 
			params[:user][:password])
		if @user.nil?
			render :new
		else
			@user.reset_session_token!
			login!(@user)
			redirect_to bands_url
		end
	end

	def destroy
		user = current_user
	    session[:session_token] = nil
	    user.reset_session_token!
	    current_user = nil
	    redirect_to user_url
	end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
	before_action :logged_in
	
	def show
		@track = Track.find(params[:id])
		render :show
	end

	def new
		@track = Track.new
		render :new
	end

	def edit
		@track = Track.find(params[:id])

		render :edit
	end

	def create
		@track = Track.new(track_params)
		if @track.save
			redirect_to track_url(@track)
		else
			flash[:errors] = @track.errors.full_messages
			render :new
		end
	end

	def update
		@track = Track.find(params[:id])
		if @track.update(track_params)
			redirect_to track_url(@track)
		else
			render :edit
		end
	end

	def destroy
		@track = Track.find(params[:id])
		@track.destroy!

		redirect_to album_url(Album.find(@track.album_id))
	end

	private
		def track_params
			params.require(:track).permit(:name, :album_id, :edition, :lyrics)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
		render :new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			login!(@user)
			redirect_to bands_url
		else
			flash[:errors] = @user.errors.full_messages
			render :new
		end
	end

	def show
		render :show
	end

	private
		def user_params
			params.require(:user).permit(:email, :password)
		end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
	def ugly_lyrics(lyrics)
		lyrics = "#{lyrics}".html_safe
		lyrics = lyrics.split("\r\n")
		lyrics.map! do |line|
			"&#9835  " + line
		end
		"<pre>#{lyrics.join("\r\n")}</pre>".html_safe
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<% if @album.persisted? %>
  <% action = album_url(@album) %>
<% else %>
  <% action = albums_url %>
<% end %>

<form action= "<%= action %>" method="POST">
  <% if @album.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
	<input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
  <label name = "album_name">Album Name
 		<input type="text" name="album[name]" value= "<%= @album.name %>">
 	</label>
  <select name="album[band_id]" id="album_band_id">
    <% Band.all.each do |band| %>
      <option value="<%= band.id %>"
      <%= "selected" if band.id == @album.band_id || (!@album.persisted? && !params[:band_id].nil? && Band.find(params[:band_id]).id == band.id) %>>
      <%= band.name %></option>
    <% end %>
  </select>
  <input type="radio" name="album[edition]" id="album_live_edition" value="Live"
  <%= "checked" if @album.edition == "Live" %>>
  <label for="album_live_edition">Live</label>
  <input type="radio" name="album[edition]" id="album_studio_edition" value="Studio"
  <%= "checked" if @album.edition == "Studio" %>>
  <label for="album_studio_edition">Studio</label>
  <input type="submit" value="Create Album">
</form>

app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render partial: 'form' %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render partial: 'form' %>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>

<ul>
	<% Track.all.each do |track| %>
		<% if track.album_id == @album.id %>
	  		<li><%= link_to track.name, track_url(track) %></li>
	  	<% end %>
	<% end %>
</ul>

<%= button_to "Create New Track!", new_album_track_url(@album), method: :get %>
<%= button_to "Delete Album!", album_url(@album), method: :delete %>
<%= button_to "Back to Albums List", band_url(Band.find(@album.band_id)), method: :get %>

app/views/bands/_form.html.erb
<% if @band.persisted? %>
	<% action = band_url(@band) %>
<% else %>
	<% action = bands_url %>
<% end %>

<form action= "<%= action %>" method="POST">
	<% if @band.persisted? %>
		<input type="hidden" name="_method" value="PATCH">
	<% end %>
	<input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
    <label name = "band_name">Band Name
   		<input type="text" name="band[name]" value= "<%= @band.name %>">
   	</label>
   	<input type="submit" value="Create Band">
</form>

app/views/bands/edit.html.erb
<h1>Edit Band</h1>
<%= render partial: 'form' %>

app/views/bands/index.html.erb
<h1>All Bands</h1>
	<% @bands.each do |band| %>
		<div><%= link_to band.name, band_url(band) %></div>
	<% end  %>
	<%= button_to "Create a New Band!", new_band_url, method: :get %>

app/views/bands/new.html.erb
<h1>New Band</h1>
<%= render partial: 'form' %>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<ul>
	<% Album.all.each do |album| %>
		<% if album.band_id == @band.id %>
	  		<li><%= link_to album.name, album_url(album) %></li>
	  	<% end %>
	<% end %>
</ul>

<%= button_to "Create New Album!", new_band_album_url(@band), method: :get %>
<%= button_to "Delete Band!", band_url(@band), method: :delete %>
<%= button_to "Back to All Bands", bands_url, method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<%= flash.now[:errors] %>
			<ul class="nav nav-pills" role="tablist">
				<% if current_user %>
					<li>
						<form action="/session" method="POST">
							<input name="authenticity_token"
							       type="hidden"
							       value="<%= form_authenticity_token %>">
							<input type="hidden" name="_method" value="DELETE">
							<button type="submit" class="btn btn-default navbar-btn">Logout</button>
						</form>
					</li>
				<% else %>
					<li>
						<form action="/session/new" method="GET">
							<input name="authenticity_token"
							       type="hidden"
							       value="<%= form_authenticity_token %>">
							<button type="submit" class="btn btn-default navbar-btn">Sign In</button>
						</form>
					</li>
					<li>
						<form action="/user/new" method="GET">
							<input name="authenticity_token"
							       type="hidden"
							       value="<%= form_authenticity_token %>">
							<button type="submit" class="btn btn-default navbar-btn">Create an Account!</button>
						</form>
					</li>
				<% end %>
			</ul>
		<%= yield %>
	</div>
</body>
</html>

app/views/notes/_form.html.erb
<h3>New Note</h3>
<form action="/notes" method="POST">
	<input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
    <input type="hidden" name="note[track_id]" value="<%= @track.id %>">
    <textarea name="note[note_text]"></textarea>
    <br />
    <input type="submit" value="Create note!">
</form>

app/views/notes/_note.html.erb
<h1>All Notes</h1>
<ul>
	<% @track.notes.each do |note| %>
		<li><%= note.note_text %> -
		<%= User.find(note.user_id).email %>
		<% if current_user == User.find(note.user_id) %>
		  <%= button_to "Delete Note", note_url(note.id), method: :delete %>
		<% end %>
		</li>
	<% end %>
</ul>

app/views/tracks/_form.html.erb
<% if @track.persisted? %>
  <% action = track_url(@track) %>
<% else %>
  <% action = tracks_url %>
<% end %>

<form action= "<%= action %>" method="POST">
  <% if @track.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
	<input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
  <label name = "track_name">Track Name
 		<input type="text" name="track[name]" value= "<%= @track.name %>">
 	</label>
  <select name="track[album_id]" id="track_album_id">
    <% Album.all.each do |album| %>
      <option value="<%= album.id %>"
      <%= "selected" if album.id == @track.album_id || (!@track.persisted? && !params[:album_id].nil? && Album.find(params[:album_id]).id == album.id) %>>
      <%= album.name %></option>
    <% end %>
  </select>
  <input type="radio" name="track[edition]" id="track_regular_edition" value="Regular"
  <%= "checked" if @track.edition == "Regular" %>>
  <label for="track_regular_edition">Regular</label>
  <input type="radio" name="track[edition]" id="track_bonus_edition" value="Bonus"
  <%= "checked" if @track.edition == "Bonus" %>>
  <label for="track_bonus_edition">Bonus</label>
  <textarea name="track[lyrics]" rows="5" cols="30"><%= @track.lyrics %></textarea>
  <input type="submit" value="Create Track">
</form>

app/views/tracks/edit.html.erb
<h1>Edit Track</h1>

<%= render partial: 'form' %>

app/views/tracks/new.html.erb
<h1>New Track</h1>
<%= render partial: 'form' %>

app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>

<p><%= ugly_lyrics(@track.lyrics) %></p>

<%= render partial: 'notes/note' %>
<%= render partial: 'notes/form' %>
<%= button_to "Delete Track!", track_url(@track), method: :delete %>
<%= button_to "Back to Tracks List", album_url(Album.find(@track.album_id)), method: :get %>

app/views/users/new.html.erb
<h1>Sign up!</h1>
<form action="/user" method="POST">
  	<input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
	<label name="user_email">E-mail
		<input type="text" name="user[email]">
	</label>
	<label name="user_password">Password
		<input type="password" name="user[password]">
	</label>
	<input type="submit" value="Create User">
</form>

app/views/users/show.html.erb
<h1>Hi 
	<% unless current_user.nil?%> 
		<%= current_user.email %>
	<% else %>
		<%= "Guest" %>
	<% end %>
</h1>